# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")

source_set("icon_standardizer") {
  public = [ "icon_standardizer.h" ]
  sources = [ "icon_standardizer.cc" ]

  deps = [
    "//base",
    "//skia",
    "//ui/gfx",
  ]
}

source_set("user_type_filter") {
  public = [ "user_type_filter.h" ]
  sources = [ "user_type_filter.cc" ]

  public_deps = [ "//base" ]

  deps = [
    "//chrome/browser/profiles:profile",
    "//content/public/browser",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "icon_standardizer_unittest.cc",
    "user_type_filter_unittest.cc",
  ]
  deps = [
    ":icon_standardizer",
    ":user_type_filter",
    "//base",
    "//chrome/browser/policy",
    "//chrome/test:test_support",
    "//content/test:test_support",
    "//skia",
    "//testing/gtest",
    "//ui/gfx",
  ]
}
