# Copyright 2016 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")

# Enable the spell checker.
enable_spellcheck = false

# Use the operating system's spellchecker rather than hunspell. This does
# not affect the "red underline" spellchecker which can consult Google's
# server-based spellcheck service.
use_browser_spellchecker = false

# Use Hunspell. Windows can use both the OS's spellchecker and Hunspell.
# Therefore, include Windows in both build flags.
use_renderer_spellchecker = false

# Whether the enhanced spellcheck service is available on the platform. This is
# effectively equal to all desktop platforms.
enable_spelling_service = false

# Only Mac has a spellcheck panel.
has_spellcheck_panel = false
