# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chrome_build.gni")
import("//build/config/ui.gni")
import("//components/signin/features.gni")

source_set("password_manager") {
  sources = []
  public = [
    "chrome_password_change_service.h",
    "chrome_password_manager_client.h",
    "chrome_webauthn_credentials_delegate.h",
    "chrome_webauthn_credentials_delegate_factory.h",
    "password_change_delegate.h",
    "password_change_service_factory.h",
    "password_field_classification_model_handler_factory.h",
  ]

  public_deps = [
    "//chrome/browser/password_manager/factories",

    # deps for public headers
    "//base",
    "//build:branding_buildflags",
    "//build:buildflag_header_h",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/webauthn",
    "//components/autofill/core/browser",
    "//components/autofill/core/common",
    "//components/credential_management:browser",
    "//components/critical_actions/core/browser",
    "//components/enterprise/buildflags",
    "//components/enterprise/connectors/core",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/password_manager/content/browser",
    "//components/password_manager/core/browser",
    "//components/password_manager/core/browser:password_manager_buildflags",
    "//components/password_manager/core/browser/features:password_features",
    "//components/prefs",
    "//components/safe_browsing:buildflags",
    "//components/signin/public/base:signin_buildflags",
    "//components/sync/service",
    "//content/public/browser",
    "//content/public/common",
    "//extensions/buildflags",
    "//ui/gfx",
    "//url",
  ]

  deps = [
    "//components/affiliations/core/browser:affiliations",
    "//components/optimization_guide/core",
  ]

  if (is_mac) {
    frameworks = [
      "Security.framework",
      "Foundation.framework",
    ]
    deps += [ "//chrome/app:branded_strings" ]
    public += [ "password_manager_util_mac.h" ]
    sources += [ "password_manager_util_mac.mm" ]
  }

  public += [
    # TODO(crbug.com/485620841): Make delegate not dependent on client and
    # move this back to /password_change.
    "password_change/password_change_actuator.h",
    "web_app_profile_switcher.h",
  ]
  public_deps += [
    "//chrome/browser/password_manager/password_change",
    "//chrome/browser/web_applications",
    "//components/webapps/common",
  ]

  if (enable_dice_support) {
    public += [ "multi_profile_credentials_filter.h" ]
  }
}

source_set("impl") {
  sources = [
    "chrome_password_change_service.cc",
    "chrome_password_manager_client.cc",
    "chrome_webauthn_credentials_delegate.cc",
    "chrome_webauthn_credentials_delegate_factory.cc",
    "password_change_service_factory.cc",
    "password_field_classification_model_handler_factory.cc",
  ]

  public_deps = [
    ":password_manager",
    "//chrome/browser:browser_public_dependencies",
  ]

  deps = [
    "//chrome/browser/affiliations",
    "//chrome/browser/autofill",
    "//chrome/browser/critical_actions",
    "//chrome/browser/device_reauth",
    "//chrome/browser/enterprise/connectors/reporting",
    "//chrome/browser/favicon",
    "//chrome/browser/history",
    "//chrome/browser/optimization_guide",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/safe_browsing",
    "//chrome/browser/signin",
    "//chrome/browser/sync",
    "//chrome/browser/sync:factories",
    "//chrome/browser/tab_contents",
    "//chrome/browser/ui/autofill",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/hats",
    "//chrome/browser/ui/passwords",
    "//chrome/browser/webauthn",
    "//chrome/common:channel_info",
    "//components/autofill/content/browser",
    "//components/autofill/core/browser",
    "//components/autofill/core/browser/integrators/password_manager",
    "//components/browsing_data/content",
    "//components/critical_actions/core/browser",
    "//components/device_reauth",
    "//components/feature_engagement/public",
    "//components/no_state_prefetch/browser",
    "//components/password_manager/content/browser",
    "//components/password_manager/core/browser",
    "//components/password_manager/core/browser:password_manager_buildflags",
    "//components/password_manager/core/browser/affiliation:affiliation_fetching",
    "//components/password_manager/core/browser/affiliation:affiliation_match_helper",
    "//components/password_manager/core/browser/features:password_features",
    "//components/password_manager/core/browser/generation:core",
    "//components/password_manager/core/browser/sharing",
    "//components/password_manager/core/common",
    "//components/policy/core/browser",
    "//components/prefs",
    "//components/profile_metrics",
    "//components/safe_browsing/core/common:features",
    "//components/sessions",
    "//components/signin/public/identity_manager",
    "//components/site_engagement/content",
    "//components/site_isolation",
    "//components/tabs:public",
    "//components/variations/service",
    "//components/version_info",
    "//extensions/buildflags",
  ]

  sources += [
    "password_change/script_password_change_actuator.cc",
    "password_change/script_password_change_actuator.h",
    "password_change_delegate_impl.cc",
    "password_change_delegate_impl.h",
    "web_app_profile_switcher.cc",
  ]
  deps += [
    "//chrome/browser/password_manager/password_change",
    "//chrome/browser/ui/passwords",
    "//chrome/browser/ui/passwords:impl",
    "//chrome/browser/ui/tabs:tab_strip",
    "//chrome/browser/ui/user_education",
    "//chrome/browser/ui/web_applications",
    "//chrome/browser/web_applications",
  ]

  if (enable_dice_support) {
    sources += [ "multi_profile_credentials_filter.cc" ]
  }
}

static_library("startup_import") {
  sources = [
    "startup_passwords_import_service.cc",
    "startup_passwords_import_service.h",
    "startup_passwords_importer.cc",
    "startup_passwords_importer.h",
  ]

  deps = [
    ":password_manager",
    "//base",
    "//chrome/browser/affiliations",
    "//chrome/browser/profiles:profile",
    "//chrome/common:channel_info",
    "//chrome/common:non_code_constants",
    "//components/affiliations/core/browser:affiliations",
    "//components/keyed_service/core",
    "//components/password_manager/core/browser/import:csv",
    "//components/password_manager/core/browser/import:importer",
    "//components/password_manager/core/browser/password_store:password_store_interface",
    "//components/password_manager/core/browser/ui",
    "//content/public/browser",
  ]
}

source_set("test_support") {
  testonly = true

  # These helpers are used by tests on all platforms, including Android.
  sources = [
    "password_change_delegate_mock.cc",
    "password_change_delegate_mock.h",
    "password_manager_test_util.cc",
    "password_manager_test_util.h",
    "passwords_navigation_observer.cc",
    "passwords_navigation_observer.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/password_manager",
    "//chrome/browser/password_manager/factories",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sync:factories",
    "//components/password_manager/core/browser",
    "//components/password_manager/core/browser:test_support",
    "//components/password_manager/core/browser/features:password_features",
    "//components/password_manager/core/browser/password_store:test_support",
    "//components/sync:test_support",
    "//components/sync/base",
    "//content/public/browser",
    "//content/test:test_support",
    "//testing/gmock",
  ]

  if (toolkit_views) {
    sources += [
      "password_manager_uitest_util.cc",
      "password_manager_uitest_util.h",
    ]
    deps += [
      "//chrome/browser/ui/autofill",
      "//chrome/browser/ui/passwords",
      "//chrome/browser/ui/passwords:impl",
      "//components/autofill/core/browser",
    ]
  }
}

source_set("test_support_ui") {
  testonly = true

  sources = [
    "password_manager_test_base.cc",
    "password_manager_test_base.h",
  ]

  public_deps = [ "//chrome/browser/ssl:cert_verifier_test_support" ]

  deps = [
    ":test_support",
    "//base",
    "//chrome/browser/password_manager",
    "//chrome/browser/password_manager/factories",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sync:factories",
    "//chrome/browser/ui",
    "//chrome/browser/ui/passwords",
    "//chrome/browser/ui/tabs:tab_enums",
    "//chrome/test:test_support_ui",
    "//components/autofill/core/browser:test_support",
    "//components/password_manager/core/browser:password_form",
    "//components/password_manager/core/browser:test_support",
    "//components/password_manager/core/browser/password_store:test_support",
    "//components/sync:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//net",
    "//net:test_support",
    "//services/network/public/mojom",
  ]

  sources += [
    "password_manager_signin_intercept_test_helper.cc",
    "password_manager_signin_intercept_test_helper.h",
  ]
  deps += [
    "//chrome/browser:browser_process",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/signin",
    "//chrome/browser/ui:ui_features",
    "//chrome/browser/ui/browser_window",
    "//chrome/common:constants",
    "//components/account_id",
    "//components/password_manager/core/browser/password_store:test_support",
    "//components/prefs",
    "//components/signin/public/identity_manager",
    "//google_apis",
  ]
}
