# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("test_support") {
  testonly = true
  configs += [ "//components/enterprise:extra_warnings" ]

  public = [
    "active_user_test_mixin.h",
    "deep_scanning_test_utils.h",
    "mock_realtime_reporting_client.h",
  ]

  sources = [
    "active_user_test_mixin.cc",
    "deep_scanning_test_utils.cc",
    "mock_realtime_reporting_client.cc",
  ]

  public_deps = [
    "//base",
    "//chrome/test:test_support_ui",
    "//components/enterprise/common/proto:connectors_proto",
    "//components/safe_browsing/core/common:safe_browsing_prefs",
    "//google_apis:test_support",
    "//net:test_support",
    "//testing/gmock",
  ]

  deps = [
    "//chrome/browser",
    "//chrome/browser/signin",
    "//chrome/test:test_support",
    "//components/enterprise/common/proto:browser_events_proto",
    "//components/enterprise/data_controls/core/browser",
    "//components/signin/public/identity_manager:test_support",
  ]
}
