# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chromeos/args.gni")
import("//build/config/ui.gni")

declare_args() {
  # Indicates support for Data Control rules.
  enterprise_data_controls = is_mac || is_linux

  # Indicates support for client certificates provisioning.
  enterprise_client_certificates = is_mac || is_linux

  # Indicates support for watermark.
  enterprise_watermark = is_mac || is_linux

  enterprise_screenshot_protection = is_mac

  enterprise_cache_encryption = is_mac || is_linux

  # Indicates support for Enterprise Proxy policy and service.
  enterprise_proxy = is_mac || is_linux
}
