# Copyright 2022 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")
import("//services/screen_ai/buildflags/features.gni")

source_set("accessibility") {
  public = [
    "pdf_ocr_metrics.h",
    "prefers_default_scrollbar_styles_prefs.h",
  ]

  public += [
    "ax_main_node_annotator_controller.h",
    "ax_main_node_annotator_controller_factory.h",
    "caption_settings_dialog.h",
    "embedded_a11y_extension_loader.h",
    "invert_bubble_prefs.h",
    "page_colors_controller.h",
    "page_colors_controller_factory.h",
  ]

  if (enable_extensions) {
    public += [ "animation_policy_prefs.h" ]
  }

  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//components/prefs",
    "//mojo/public/cpp/bindings",
    "//net",
  ]

  public_deps += [ "//components/component_updater" ]

  public_deps += [
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/screen_ai:screen_ai_install_state",
    "//components/pref_registry",
    "//ui/accessibility/platform",
    "//ui/native_theme",
  ]
}

source_set("impl") {
  sources = [
    "pdf_ocr_metrics.cc",
    "prefers_default_scrollbar_styles_prefs.cc",
  ]

  deps = [ "//chrome/browser/language" ]

  sources += [
    "ax_main_node_annotator_controller.cc",
    "ax_main_node_annotator_controller_factory.cc",
    "embedded_a11y_extension_loader.cc",
    "invert_bubble_prefs.cc",
    "page_colors_controller.cc",
    "page_colors_controller_factory.cc",
  ]
  deps += [
    "//chrome/browser/extensions",
    "//chrome/browser/on_device_translation",
    "//chrome/browser/screen_ai:screen_ai_service_router_factory",
    "//chrome/browser/ui",
    "//chrome/browser/ui/browser_window",
    "//components/on_device_translation",
  ]

  deps += [ "//chrome/browser/component_updater" ]

  if (is_mac) {
    sources += [ "caption_settings_dialog_mac.cc" ]
  }

  if (enable_extensions) {
    sources += [ "animation_policy_prefs.cc" ]
  }

  public_deps = [
    ":accessibility",
    "//chrome/browser:browser_public_dependencies",
  ]

  deps += [
    "//base",
    "//chrome/browser:browser_process",
    "//chrome/browser/manta",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/tab_contents",
    "//components/language/core/browser",
    "//components/manta",
    "//components/pref_registry",
    "//components/sync_preferences",
    "//components/update_client",
    "//content/public/browser",
    "//ui/accessibility",
    "//ui/accessibility/platform",
  ]

  allow_circular_includes_from =
      [ "//chrome/browser:browser_public_dependencies" ]
}

source_set("unit_tests") {
  testonly = true
  sources = []
  if (is_linux || is_mac || is_win) {
  }
  deps = [
    ":accessibility",
    ":impl",
    "//base/test:test_support",
    "//chrome/test:test_support",
    "//testing/gtest",
  ]
  if (is_linux || is_mac || is_win) {
    deps += [ "//chrome/browser/component_updater" ]
  }
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  configs += [ "//build/config/compiler:no_exit_time_destructors" ]
  data_deps = []
  sources = [
    "ax_main_node_annotator_controller_browsertest.cc",
    "canvas_accessibility_browsertest.cc",
    "interstitial_accessibility_browsertest.cc",
    "page_colors_controller_browsertest.cc",
  ]

  if (enable_extensions) {
    sources += [ "embedded_a11y_extension_loader_browsertest.cc" ]
  }

  deps = [
    ":accessibility",
    ":impl",
    "//chrome/browser/profiles:misc",
    "//chrome/browser/ui/browser_window",
    "//chrome/test:test_support",
    "//content/test:browsertest_support",
    "//content/test:test_support",
  ]

  deps += [
    "//chrome/browser/screen_ai:screen_ai_service_router_factory",
    "//services/screen_ai/public/cpp:utilities",
  ]

  if (enable_screen_ai_browsertests) {
    data_deps += [ "//third_party/screen-ai:screen_ai" ]
  }
}
