# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("constants") {
  sources = [ "pref_names.h" ]

  deps = [
    "//base",
    "//components/prefs",
    "//media",
  ]
}

source_set("utils") {
  sources = [
    "caption_util.cc",
    "caption_util.h",
  ]

  deps = [
    ":constants",
    "//base",
    "//components/prefs",
    "//media",
    "//ui/base",
    "//ui/native_theme",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "caption_util_unittest.cc" ]

  deps = [
    ":constants",
    ":utils",
    "//base",
    "//base/test:test_support",
    "//components/prefs:test_support",
    "//media",
    "//testing/gtest",
    "//ui/base",
    "//ui/native_theme",
  ]
}
