# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("banners") {
  sources = []
  public_deps = [
    "//base",
    "//components/webapps/browser",
  ]

  sources += [ "app_banner_manager_desktop.h" ]
  public_deps += [
    "//chrome/browser/ui/web_applications",
    "//chrome/browser/web_applications",
    "//components/webapps/common",
    "//content/public/browser",
  ]
}

# TODO(crbug.com/353332589): :banners and :impl can be merged once
# c/b/ui/tabs_helpers.cc ever gets built out of //c/b/ui:ui, otherwise
# it causes circular dependencies.
source_set("impl") {
  sources = []
  deps = [
    ":banners",
    "//chrome/browser/profiles:profile",
    "//third_party/blink/public/common",
  ]

  sources += [ "app_banner_manager_desktop.cc" ]
  deps += [
    "//chrome/browser/ui",
    "//chrome/browser/ui/web_applications",
    "//chrome/browser/web_applications",
    "//chrome/browser/web_applications/mojom:mojom_web_apps_enum",
    "//chrome/browser/web_applications/proto",
    "//components/webapps/browser:constants",
    "//extensions/browser",
    "//extensions/common:common_constants",
  ]
  public_deps = [ "//chrome/browser:browser_public_dependencies" ]
}

source_set("test_support") {
  testonly = true
  sources = []
  deps = []

  sources += [
    "test_app_banner_manager_desktop.cc",
    "test_app_banner_manager_desktop.h",
  ]
  public_deps = [ ":banners" ]
  deps += [
    "//base/test:test_support",
    "//chrome/browser",
    "//chrome/browser/webapps:desktop",
    "//chrome/browser/webapps:desktop_impl",
    "//components/password_manager/content/common",
    "//components/webapps/browser",
    "//components/webapps/browser:webapps_client",
    "//content/public/browser",
    "//testing/gmock",
    "//third_party/blink/public/common:headers",
  ]
}
