group("password_manager") {
  public_deps = [
    ":factory",
    ":public",
  ]
}

source_set("factory") {
  public_deps = [ ":public" ]
}

source_set("public") {
  deps = [
    "//base",
    "//components/password_manager/core/browser",
  ]

  public_deps = [ "//url" ]

  sources = [ "touch_to_fill_password_manager_view.h" ]
}
