# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("signals") {
  configs += [ "//components/enterprise:extra_warnings" ]

  public_deps = [
    "//base",
    "//chrome/browser/enterprise/core",
    "//components/enterprise/device_trust/core/attestation:types",
    "//components/enterprise/device_trust/core/signals",
  ]
}

source_set("test_support") {
  testonly = true
  configs += [ "//components/enterprise:extra_warnings" ]

  public_deps = [
    ":signals",
    "//components/enterprise/device_trust/core/signals:test_support",
    "//testing/gmock",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = []
  deps = []
}
