# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")

assert(!is_android)

source_set("app_icon") {
  sources = [
    "app_icon_factory.cc",
    "app_icon_factory.h",
    "app_icon_loader.cc",
    "app_icon_loader.h",
  ]

  deps = [
    ":util",
    "//base",
    "//chrome/app/theme:chrome_unscaled_resources",
    "//chrome/browser/apps:icon_standardizer",
    "//chrome/browser/favicon",
    "//chrome/browser/icon_transcoder",
    "//chrome/browser/profiles",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/resources:app_icon_resources",
    "//chrome/browser/web_applications",
    "//chrome/common",
    "//components/app_constants",
    "//components/favicon/core",
    "//components/favicon_base",
    "//components/keyed_service/content",
    "//components/services/app_service",
    "//components/webapps/common",
    "//content/public/browser",
  ]

  if (enable_extensions) {
    deps += [
      "//extensions:extensions_browser_resources",
      "//extensions/browser",
      "//extensions/common",
    ]
  }

  public_deps = [ "//chrome/browser:browser_public_dependencies" ]
}

source_set("util") {
  sources = [
    "app_icon_util.cc",
    "app_icon_util.h",
    "dip_px_util.cc",
    "dip_px_util.h",
  ]

  deps = [
    "//base",
    "//components/services/app_service",
    "//services/data_decoder/public/cpp",
    "//ui/base",
    "//ui/display",
    "//ui/gfx",
  ]
}
