# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//testing/libfuzzer/fuzzer_test.gni")

source_set("export") {
  sources = [
    "csv_writer.cc",
    "csv_writer.h",
    "export_progress_status.h",
    "password_csv_writer.cc",
    "password_csv_writer.h",
    "password_manager_exporter.cc",
    "password_manager_exporter.h",
  ]
  deps = [
    "//base",
    "//components/affiliations/core/browser:affiliations",
    "//components/password_manager/core/browser:metrics_util",
    "//components/password_manager/core/browser/ui",
    "//components/sync/base:features",
  ]
  configs += [ "//build/config/compiler:wexit_time_destructors" ]
}
