# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//extensions/buildflags/buildflags.gni")

source_set("history") {
  public = [
    "chrome_history_backend_client.h",
    "chrome_history_client.h",
    "domain_diversity_reporter_factory.h",
    "history_service_factory.h",
    "history_tab_helper.h",
    "history_utils.h",
    "profile_based_browsing_history_driver.h",
    "top_sites_factory.h",
    "web_history_service_factory.h",
  ]
  public_deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/bookmarks/browser",
    "//components/history/core/browser",
    "//components/keyed_service/core",
    "//components/language_detection/content/browser:host",
    "//components/sessions",
    "//content/public/browser",
  ]
}

source_set("impl") {
  sources = [
    "chrome_history_backend_client.cc",
    "chrome_history_client.cc",
    "domain_diversity_reporter_factory.cc",
    "history_service_factory.cc",
    "history_tab_helper.cc",
    "history_utils.cc",
    "profile_based_browsing_history_driver.cc",
    "top_sites_factory.cc",
    "web_history_service_factory.cc",
  ]
  public_deps = [
    ":history",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "//base",
    "//chrome/browser/bookmarks",
    "//chrome/browser/complex_tasks",
    "//chrome/browser/engagement",
    "//chrome/browser/preloading/prefetch/no_state_prefetch",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/renderer_host",
    "//chrome/browser/search_engines",
    "//chrome/browser/signin",
    "//chrome/browser/sync:factories",
    "//chrome/browser/ui/profiles",
    "//chrome/common",
    "//chrome/common:constants",
    "//components/bookmarks/browser",
    "//components/browsing_data/core",
    "//components/dom_distiller/core",
    "//components/history/content/browser",
    "//components/history/core/browser",
    "//components/history/core/common",
    "//components/history/metrics",
    "//components/keyed_service/core",
    "//components/no_state_prefetch/browser",
    "//components/policy/core/common:common_constants",
    "//components/pref_registry",
    "//components/prefs",
    "//components/search_engines",
    "//components/sessions",
    "//components/strings:components_strings",
    "//components/sync/service",
    "//components/webapps/browser",
    "//content/public/browser",
    "//extensions/buildflags",
    "//net",
    "//third_party/blink/public/common",
    "//ui/base",
    "//url",
  ]

  if (enable_extensions_core) {
    deps += [ "//chrome/browser/extensions" ]
  }

  if (is_android) {
    deps += [
      ":jni_headers",
      "//chrome/browser/feed",
      "//chrome/browser/flags:flags_android",
      "//chrome/browser/ui/android/tab_model:impl",
    ]
  } else {
    deps += [ "//chrome/browser/ui/browser_window" ]
  }
}

source_set("test_support") {
  testonly = true
  sources = [
    "history_test_utils.cc",
    "history_test_utils.h",
  ]
  public_deps = [
    ":history",
    "//base",
    "//components/history/core/browser",
  ]
  deps = [
    "//chrome/browser/profiles:profile",
    "//content/test:test_support",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "history_tab_helper_unittest.cc" ]
  deps = [
    "//components/tabs:test_support",
    ":history",
    "//base",
    "//base/test:test_support",
    "//chrome/browser",
    "//chrome/common:chrome_features",
    "//chrome/test:test_support",
    "//components/history/core/browser",
    "//content/public/browser",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/blink/public/common",
    "//ui/base",
  ]

}

if (!is_android) {
  source_set("browser_tests") {
    testonly = true
    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
    sources = [
      "history_browsertest.cc",
      "redirect_browsertest.cc",
    ]
    deps = [
      ":history",
      ":test_support",
      "//base",
      "//base/test:test_support",
      "//chrome/app:command_ids",
      "//chrome/browser",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/renderer_host",
      "//chrome/browser/search_engines",
      "//chrome/browser/sync/test/integration:sync_integration_test_support",
      "//chrome/browser/ui",
      "//chrome/browser/ui:ui_features",
      "//chrome/browser/ui:view_ids",
      "//chrome/common",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
      "//components/history/core/browser",
      "//components/history/core/common",
      "//components/history/core/test",
      "//components/prefs",
      "//components/search_engines",
      "//content/public/browser",
      "//content/test:test_support",
      "//net:test_support",
      "//testing/gtest",
      "//third_party/blink/public/common",
      "//ui/base",
      "//ui/events",
      "//ui/webui:test_support",
      "//url",
    ]
  }
}
