# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/browser/buildflags.gni")

assert(!is_android)

source_set("shortcuts") {
  public = [ "shortcut_icon_generator.h" ]
  sources = [ "shortcut_icon_generator.cc" ]
  public_deps = [ "//chrome/browser:browser_public_dependencies" ]
  deps = [
    "//chrome/app/resources:platform_locale_settings",
    "//components/url_formatter",
    "//net",
    "//ui/base",
    "//ui/gfx",
  ]

  public += [ "create_shortcut_for_current_web_contents_task.h" ]

  sources += [
    "create_shortcut_for_current_web_contents_task.cc",
    "document_icon_fetcher_task.cc",
    "document_icon_fetcher_task.h",
    "icon_badging.cc",
    "icon_badging.h",
    "shortcut_creator.cc",
    "shortcut_creator.h",
  ]

  deps += [
    "//base",
    "//build:branding_buildflags",
    "//chrome/app/theme:chrome_unscaled_resources_grit",
    "//chrome/browser/profiles:profile",
    "//chrome/common:channel_info",
    "//chrome/common:chrome_features",
    "//components/webapps/common",
    "//components/webapps/common:mojo_bindings",
    "//content/public/browser",
    "//crypto",
    "//mojo/public/cpp/bindings",
    "//skia",
    "//third_party/blink/public/common",
    "//url",
  ]

  friend = [
    ":browser_tests",
    ":test_support",
    ":unit_tests",
  ]

  if (is_mac) {
    public += [
      "chrome_webloc_file.h",
      "platform_util_mac.h",
    ]
    sources += [
      "chrome_webloc_file.mm",
      "platform_util_mac.mm",
      "shortcut_creator_mac.mm",
    ]
  }

  if (is_linux) {
    sources += [
      "linux_xdg_wrapper.h",
      "linux_xdg_wrapper_impl.cc",
      "linux_xdg_wrapper_impl.h",
      "shortcut_creator_linux.cc",
      "shortcut_creator_linux.h",
    ]
    deps += [ "//chrome/browser:shell_integration_linux" ]
  }
}

source_set("test_support") {
  testonly = true

  public = [
    "shortcut_creation_test_support.h",
  ]
  public_deps = [
    ":shortcuts",
    "//base",
    "//base/test:test_support",
    "//skia",
    "//url",
  ]
  deps = [ "//ui/gfx/codec" ]
  sources = []

  if (is_linux) {
    public += [
      "fake_linux_xdg_wrapper.h",
    ]
    sources += [
      "fake_linux_xdg_wrapper.cc",
    ]
    deps += [
      "//chrome/browser",
      "//chrome/browser:chrome_browser_main",
      "//chrome/browser:shell_integration_linux",
    ]
  }
  if (is_mac) {
  }
}
