# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD - style license that can be
# found in the LICENSE file.

source_set("tab_group_sync") {
  public = [
    "tab_group_sync_tab_state.h",
    "tab_group_sync_utils.h",
    "tab_group_trial.h",
  ]

  public_deps = [
    "//base",
    "//components/saved_tab_groups/public",
    "//content/public/browser",
  ]
}

source_set("impl") {
  sources = [
    "tab_group_sync_tab_state.cc",
    "tab_group_sync_utils.cc",
    "tab_group_trial.cc",
  ]

  public_deps = [
    ":tab_group_sync",
    "//chrome/browser:browser_public_dependencies",
  ]

  deps = [
    "//chrome/browser/metrics",
    "//chrome/common:mojo_bindings",
    "//components/saved_tab_groups/public:features",
    "//components/variations",
    "//content/public/browser",
    "//net",
    "//third_party/blink/public/common",
  ]

}

source_set("factories") {
  sources = [ "tab_group_sync_service_factory.h" ]
  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//components/keyed_service/content",
  ]
}

source_set("factories_impl") {
  sources = [ "tab_group_sync_service_factory.cc" ]
  deps = [
    ":factories",
    ":tab_group_sync",
    "//base",
    "//chrome/browser/data_sharing",
    "//chrome/browser/optimization_guide",
    "//chrome/browser/profiles",
    "//chrome/browser/signin",
    "//chrome/browser/sync",
    "//chrome/browser/sync:factories",
    "//chrome/browser/tab_group_sync:utils",
    "//chrome/common:channel_info",
    "//components/collaboration/internal:collaboration_finder",
    "//components/data_sharing/public:features",
    "//components/keyed_service/content",
    "//components/optimization_guide/proto:optimization_guide_proto",
    "//components/saved_tab_groups/delegate",
    "//components/saved_tab_groups/internal",
    "//components/saved_tab_groups/public",
    "//components/sync",
    "//components/sync_device_info",
  ]

  if (!is_android) {
    deps += [ "//chrome/browser/ui/tabs/saved_tab_groups" ]
  } else {
    deps += [
      "//chrome/browser/tab_group_sync:android",
    ]
  }

  public_deps = [ "//chrome/browser:browser_public_dependencies" ]
}

source_set("utils") {
  sources = [
    "feature_utils.cc",
    "feature_utils.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles",
    "//components/prefs",
    "//components/saved_tab_groups/public:features",
    "//components/saved_tab_groups/public:prefs",
  ]

}

source_set("unit_tests") {
  testonly = true

  sources = [
    "tab_group_sync_service_factory_unittest.cc",
    "tab_group_sync_utils_unittest.cc",
  ]

  deps = [
    ":factories",
    ":factories_impl",
    ":impl",
    ":tab_group_sync",
    "//base",
    "//chrome/test:test_support",
    "//components/saved_tab_groups/public:features",
    "//content/test:test_support",
    "//net",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
