# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//chrome/browser/buildflags.gni")

source_set("shortcuts") {
  public = [ "create_desktop_shortcut.h" ]
  public_deps = [
    "//base",
    "//ui/base",
    "//ui/base/interaction",
  ]
}

source_set("impl") {
  sources = [
    "create_desktop_shortcut.cc",
    "create_desktop_shortcut_delegate.cc",
    "create_desktop_shortcut_delegate.h",
  ]
  public_deps = [
    ":shortcuts",
    "//chrome/browser:browser_public_dependencies",
  ]
  deps = [
    "//chrome/app:branded_strings",
    "//chrome/app:generated_resources",
    "//chrome/browser/picture_in_picture",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/shortcuts",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/dialogs:browser_dialogs",
    "//chrome/browser/ui/shortcuts",
    "//chrome/browser/ui/views/controls",
    "//components/constrained_window",
    "//components/prefs",
    "//components/web_modal",
    "//content/public/browser",
    "//ui/gfx",
    "//ui/views",
    "//url",
  ]
}
