# Copyright 2019 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/util/process_version.gni")
import("//chrome/updater/apply_updater_branding.gni")

# Run 'gn check out\Default --check-generated //chrome/updater/*' every time
# dependencies are modified until a presubmit is written to automatically
# check that the C++ includes match the build dependency graph.

if (is_mac || is_linux) {
  if (is_mac) {
    source_set("ks_ticket") {
      sources = [
        "mac/setup/ks_tickets.h",
        "mac/setup/ks_tickets.mm",
      ]

      deps = [ "//base" ]
    }
  }

  # Set of sources that are required to create an executable based on `App`.
  source_set("constants_header") {
    sources = [ "constants.h" ]

    public_deps = [ "//base" ]
    deps = [ "//components/update_client" ]
  }

  source_set("external_constants") {
    sources = [
      "external_constants.cc",
      "external_constants.h",
      "external_constants_default.cc",
      "external_constants_default.h",
    ]

    deps = [
      ":branding_header",
      ":constants_header",
      "//base",
      "//build:branding_buildflags",
      "//components/crx_file",
      "//url",
    ]
  }

  source_set("constants_prod") {
    sources = [
      "constants_prod.cc",
      "external_constants_prod.cc",
    ]

    deps = [
      ":constants_header",
      ":external_constants",
      "//base",
    ]
  }

  source_set("constants_test") {
    sources = [
      "constants_test.cc",
      "external_constants_override.cc",
      "external_constants_override.h",
    ]

    deps = [
      ":branding_header",
      ":constants_header",
      ":external_constants",
      ":public_sources",
      ":version_header",
      "//base",
      "//components/crx_file",
      "//url",
    ]
  }

  process_version("version_header") {
    sources = [ "//chrome/VERSION" ]
    template_file = "updater_version.h.in"
    output = "$target_gen_dir/updater_version.h"
  }

  apply_updater_branding("branding_header") {
    template_file = "updater_branding.h.in"
    output = "$target_gen_dir/updater_branding.h"
  }

  source_set("browser_sources") {
    sources = [
      # Ideally we would have :constants_prod as a public_dep. However, this
      # pulls in a static initializer, which is not allowed in Chromium.
      "constants_prod.cc",
    ]

    public_deps = [
      ":public_sources",
      ":tagging",
    ]
    deps = [ ":constants_header" ]

    visibility = [
      "//chrome/browser",
      "//chrome/browser/component_updater:unit_tests",
      "//chrome/browser/ui",
      "//chrome/browser/ui/webui/help:*",
      "//chrome/browser/updater:*",
      "//chrome/enterprise_companion:*",
      "//chrome/enterprise_companion/device_management_storage:*",
      "//chrome/test:*",
      "//chrome/test:unit_tests",
    ]
  }

  source_set("tagging") {
    sources = [
      "certificate_tag.cc",
      "certificate_tag.h",
      "certificate_tag_internal.h",
      "pkg_tag.cc",
      "pkg_tag.h",
      "tag.cc",
      "tag.h",
      "tag_internal.h",
    ]

    deps = [
      "//base",
      "//crypto",
    ]
  }

  source_set("public_util") {
    public = [
      "updater_scope.h",
      "util/path_util.h",
    ]
    sources = [ "util/path_util.cc" ]
    if (is_linux) {
      sources += [ "util/linux_path_util.cc" ]
    }
    if (is_mac) {
      sources += [
        "util/mac_path_util.h",
        "util/mac_path_util.mm",
      ]
    }
    deps = [
      ":branding_header",
      "//base",
    ]
  }

  source_set("public_sources") {
    sources = [
      "branded_constants.h",
      "constants.h",
      "enum_traits.h",
      "get_updater_scope.cc",
      "get_updater_scope.h",
      "ipc/ipc_names.h",
      "ipc/ipc_support.cc",
      "ipc/ipc_support.h",
      "ipc/update_service_dialer.h",
      "ipc/update_service_proxy.cc",
      "ipc/update_service_proxy.h",
      "ipc/update_service_proxy_impl.h",
      "ipc/update_service_proxy_mojo.cc",
      "ipc/update_service_proxy_mojo.h",
      "registration_data.h",
      "service_proxy_factory.h",
      "update_service.cc",
      "update_service.h",
      "util/util.cc",
      "util/util.h",
    ]

    public_deps = [ ":public_util" ]

    deps = [
      ":branding_header",
      ":tagging",
      ":version_header",
      "//base",
      "//chrome/enterprise_companion:installer_paths",
      "//chrome/updater/mojom",
      "//components/named_mojo_ipc_server",
      "//components/policy/core/common:common_constants",
      "//components/update_client",
      "//mojo/core/embedder",
      "//url",
    ]

    if (is_linux) {
      sources += [
        "ipc/ipc_names_linux.cc",
        "ipc/update_service_dialer_linux.cc",
        "linux/ipc_constants.cc",
        "linux/ipc_constants.h",
        "util/linux_util.cc",
        "util/linux_util.h",
      ]
    }

    if (is_mac) {
      sources += [
        "ipc/ipc_names_mac.mm",
        "ipc/update_service_dialer_mac.cc",
        "mac/privileged_helper/service_protocol.h",
        "mac/setup/keystone.h",
        "mac/setup/keystone.mm",
        "util/mac_util.h",
        "util/mac_util.mm",
      ]

      deps += [ ":ks_ticket" ]

      frameworks = [ "Foundation.framework" ]
    }

    if (is_posix) {
      sources += [
        "ipc/update_service_dialer_posix.cc",
        "ipc/update_service_dialer_posix.h",
        "posix/setup.h",
        "util/posix_util.cc",
        "util/posix_util.h",
      ]
    }
  }
}
